In [6]:
import torch
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4
max_iters = 1000
# eval_interval = 2500
learning_rate = 3e-4
eval_iters = 250

cpu


In [7]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))
print(chars)
vocab_size = len(chars)



['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [8]:
string_to_int = { ch:i for i,ch in enumerate(chars) }
int_to_string = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])


In [9]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs:')
# print(x.shape)
print(x)
print('targets:')
print(y)

inputs:
tensor([[11,  0,  0,  3, 33,  5, 66,  1],
        [49, 58, 73,  1, 68, 67, 58,  1],
        [58, 54, 56, 61, 62, 67, 60,  1],
        [ 1, 73, 61, 58,  1, 44, 62, 67]])
targets:
tensor([[ 0,  0,  3, 33,  5, 66,  1, 60],
        [58, 73,  1, 68, 67, 58,  1, 61],
        [54, 56, 61, 62, 67, 60,  1, 73],
        [73, 61, 58,  1, 44, 62, 67,  1]])


In [10]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [11]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        
    def forward(self, index, targets=None):
        logits = self.token_embedding_table(index)
        
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        
        return logits, loss
    
    def generate(self, index, max_new_tokens):
        # index is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self.forward(index)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            index_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            index = torch.cat((index, index_next), dim=1) # (B, T+1)
        return index

model = BigramLanguageModel(vocab_size)
m = model.to(device)

context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


uUcQHT&q1K
UYFsQ1,B!wGm"iMBHGN:OWBr
'UKDNqr4YyXDTB[O:bhB?Df-2MCGoH8Dzu8,GnioFb3Jzzjio?] AEy0ocw
BN9[vzO'g._Uz47VBPoJqm0x*.5jcOnb2rTSKBy]C11c.apQ:r*idG)XJ 'J7VTBxM
qP;TH X8e7M;j]qb0ffTmG.Yr7gx.5hr(Q:_UPH.rf!7P
'A8 Ddl2G_.0M;ZaPe(qUnzMSk2ZLt: D4W7pkODZ8uX lOcqZCe7?[yXkwf_7Ge?P(MC:S,f'&l6 4nHaP*, e5kQvA0hB(r6BbDr(n.PqcoQiDoFI'-7qle(rl88S07G(K9TErTODqV,WcHTBw8B)!Cgx1;o9m0sERT?kX_UwcRJFm03VDNQNJ3V*HC8'rff3s)]drOELGz7kB(K'SsV
gYKW o2?.88G54(n'DZQVX e(K9a3sP]E]Hdl8s4YN_2DzWUH1)w9LO"Zv4d42GM P;oUi


In [12]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step: {iter}, train loss: {losses['train']:.3f}, val loss: {losses['val']:.3f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
print(loss.item())

step: 0, train loss: 4.952, val loss: 4.916
step: 250, train loss: 4.853, val loss: 4.849
step: 500, train loss: 4.786, val loss: 4.804
step: 750, train loss: 4.722, val loss: 4.740
4.693192481994629


need to familiarize audience with optimizers (AdamW, Adam, SGD, MSE…) no need to jump into the formulas, just what the optimizer does for us and some of the differences/similarities between them*

    Mean Squared Error (MSE): MSE is a common loss function used in regression problems, where the goal is to predict a continuous output. It measures the average squared difference between the predicted and actual values, and is often used to train neural networks for regression tasks.
    Gradient Descent (GD): is an optimization algorithm used to minimize the loss function of a machine learning model. The loss function measures how well the model is able to predict the target variable based on the input features. The idea of GD is to iteratively adjust the model parameters in the direction of the steepest descent of the loss function
    Momentum: Momentum is an extension of SGD that adds a "momentum" term to the parameter updates. This term helps smooth out the updates and allows the optimizer to continue moving in the right direction, even if the gradient changes direction or varies in magnitude. Momentum is particularly useful for training deep neural networks.
    RMSprop: RMSprop is an optimization algorithm that uses a moving average of the squared gradient to adapt the learning rate of each parameter. This helps to avoid oscillations in the parameter updates and can improve convergence in some cases.
    Adam: Adam is a popular optimization algorithm that combines the ideas of momentum and RMSprop. It uses a moving average of both the gradient and its squared value to adapt the learning rate of each parameter. Adam is often used as a default optimizer for deep learning models.
    AdamW: AdamW is a modification of the Adam optimizer that adds weight decay to the parameter updates. This helps to regularize the model and can improve generalization performance. We will be using the AdamW optimizer as it best suits the properties of the model we will train in this video.

find more optimizers and details at torch.optim

In [13]:
context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


m77G?jxP;T2_dG4V PqEo pkS3H rBHEuduMQR2kC554;V5g!ANc71"y][v35GLxa2G_FaQN5c2&;g4ErcU5TOcjay5Cgs4y0.c7bl,S AE]&*[S9R;TI4UK'_U*:VN& K'UQ4XTZQR3g(IT*b
dXzMmTO4HR
_429a-s)Sw9awGQav6y6_UlvpA0M:SS4i,Uk8C'DG"4UlhB*H 
AE3QUcBcgs!lbi!7JFqm4H g4GeS,oFa-LtpRZaw:KRfie]m0&vVud6X.4Q:qf6*zh'ZP?kv'w)*z2xQuyK5(Kvod:bC
M:B1_dlvrhgQQWVI:Kkgcs.rR(-Cf?k!H1hP[dIsEz(;nm0sGib0&l8GF5kBhkgWw)RGv*gI9c772?*lrwL*HtR'OBwSNQ-3f-p]Md9J!3YE]D?nH !C.ag(L1p][lxF',xPoxK&j]yBg3jkhrf gWe0WK*qmTp
Yw
f6[v_kXjo5kud8!lP;o*G.-hm6o2?
